### ISSUE TITLE
field message not found in type config.plain

### ISSUE THREAD

**Issue by davie5201314** [guyongquan/webhook-adapter#1]
微信机器人自定义模板会报错：
`global:
  resolve_timeout: 5m
receivers:
- name: "null"
- name: webhook
  webhook_configs:
  - url: http://prometheus-webhook-dingtalk.monitoring.svc.cluster.local:8060/adapter/wx
    send_resolved: true
    message: '{{ template "webchat.html" . }}'

route:
  group_by:
  - job
  group_interval: 5m
  group_wait: 1m
  receiver: webhook
  repeat_interval: 5m
  routes:
  - match:
      alertname: Watchdog
    receiver: "null"
templates:
- '*.tmpl'
`
模板如下：
{{ define "webchat.html" }}
{{ range $i, $alert :=.Alerts }}
========监控报警==========
告警状态：{{ .Status }}
告警级别：{{ $alert.Labels.severity }}
告警类型：{{ $alert.Labels.alertname }}
告警主题：{{ $alert.Annotations.summary }}
告警主机：{{ $alert.Labels.instance }}
告警详情：{{ $alert.Annotations.message }}
告警时间：{{ $alert.StartsAt.Format "2006-01-02 15:04:05" }}
========end=============
{{ end }}
{{ end }}
日志报错：
caller=coordinator.go:124 component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config/alertmanager.yaml err="yaml: unmarshal errors:\n  line 9: field message not found in type config.plain"

**Comment by guyongquan** [comment]
不需要webchat.html这个模板，不用配置message字段
