### ISSUE TITLE
怎么添加代理，env设置不生效

### ISSUE THREAD

**Issue by gaomiup20** [guyongquan/webhook-adapter#7]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: prometheus-webhook
  name: prometheus-webhook
  namespace: monitoring
spec:
  selector:
    matchLabels:
      run: prometheus-webhook
  template:
    metadata:
      labels:
        run: prometheus-webhook
    spec:
      containers:
      - args:
        - --adapter=/app/prometheusalert/wx.js=/adapter/wx=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx
        image: 10.124.144.10/webhook-adapter/wechat:v.0.1 
        name: prometheus-webhook
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        #######key必须是小写#######
        - name: http_proxy
          value: http://10.191.131.12:3128
        - name: https_proxy
          value: http://10.191.131.12:3128
        resources:
          limits:
            memory: 500Mi

最终效果

![image](https://user-images.githubusercontent.com/26083944/106256768-a9c68000-6256-11eb-8c3a-e0c1228ee35b.png)
![image](https://user-images.githubusercontent.com/26083944/106256793-b0ed8e00-6256-11eb-8f95-9be32551e45f.png)

**Comment by gaomiup20** [comment]
解决

**Comment by plutoid** [comment]
好奇最后是怎么解决的，遇到同样的问题。
